channels:
  - conda-forge
  - bioconda
dependencies:
  - amas=1.0=pyh864c0ab_0
  - astral-tree=5.7.8=hdfd78af_1
  - augustus=3.5.0=pl5321h57ba348_8
  - bamtools=2.5.3=he132191_0
  - bbmap=39.28=he5f24ec_0
  - binutils_impl_linux-64=2.44=h4bf12b8_1
  - bioconductor-ggtree=3.14.0=r44hdfd78af_0
  - bioconductor-treeio=1.30.0=r44hdfd78af_0
  - biopython=1.85=py311h9ecbd09_1
  - blast=2.16.0=h66d330f_5
  - busco=5.8.0=pyhdfd78af_0
  - cdbtools=0.99=h077b44d_12
  - click=8.2.1=pyh707e725_0
  - clustalw=2.1=h9948957_12
  - colorama=0.4.6=pyhd8ed1ab_1
  - coloredlogs=15.0.1=pyhd8ed1ab_4
  - configargparse=1.7.1=pyhe01879c_0
  - diamond=2.1.13=h13889ed_0
  - entrez-direct=22.4=he881be0_0
  - fastp=0.25.0=heae3180_0
  - gawk=5.3.1=hcd3d067_0
  - gotree=0.5.0=he881be0_0
  - graphite2=1.3.14=h5888daf_0
  - hmmer=3.4=hb6cb901_4
  - iqtree=3.0.1=h503566f_0
  - mafft=7.526=h4bc722e_0
  - matplotlib=3.10.5=py311h38be061_0
  - matplotlib-base=3.10.5=py311h0f3be63_0
  - metaeuk=7.bba0d80=pl5321hd6d6fdc_2
  - minimap2=2.30=h577a1d6_0
  - miniprot=0.18=h577a1d6_0
  - mummer=3.23=pl5321h503566f_21
  - muscle=3.8.1551=h9948957_9
  - ncbi-datasets-cli=18.5.0=ha770c72_0
  - ncbi-vdb=3.2.1=h9948957_0
  - networkx=3.5=pyhe01879c_0
  - newick_utils=1.6=hd747bf3_9
  - numpy=2.3.2=py311h2e04523_0
  - pal2nal=14.1=pl5321hdfd78af_3
  - pandas=2.3.1=py311hed34c8f_0
  - pango=1.56.4=hadf4263_0
  - parallel-fastq-dump=0.6.7=pyhdfd78af_0
  - prodigal=2.6.3=h577a1d6_11
  - python=3.11.0=he550d4f_1_cpython
  - r-ape=5.8_1=r44hb79369c_0
  - r-aplot=0.2.8=r44hc72bb7e_0
  - r-askpass=1.2.1=r44h2b5f3a1_0
  - r-assertthat=0.2.1=r44hc72bb7e_5
  - r-base
  - r-bit=4.6.0=r44h2b5f3a1_0
  - r-bit64=4.6.0_1=r44h2b5f3a1_0
  - r-bms=0.3.5=r44hc72bb7e_4
  - r-cli=3.6.5=r44h93ab643_0
  - r-clipr=0.8.0=r44hc72bb7e_3
  - r-colorspace=2.1_1=r44hdb488b9_0
  - r-cpp11=0.5.2=r44h785f33e_1
  - r-crayon=1.5.3=r44hc72bb7e_1
  - r-curl=6.4.0=r44h10955f1_1
  - r-digest=0.6.37=r44h0d4f4ea_0
  - r-dplyr=1.1.4=r44h0d4f4ea_1
  - r-ellipsis=0.3.2=r44hb1dbf0f_3
  - r-fansi=1.0.6=r44hb1dbf0f_1
  - r-farver=2.1.2=r44ha18555a_1
  - r-fs=1.6.6=r44h93ab643_0
  - r-generics=0.1.4=r44hc72bb7e_0
  - r-ggfun=0.2.0=r44hc72bb7e_0
  - r-ggplot2=3.5.2=r44hc72bb7e_0
  - r-ggplotify=0.1.2=r44hc72bb7e_1
  - r-glue=1.8.0=r44h2b5f3a1_0
  - r-gridextra=2.3=r44hc72bb7e_1006
  - r-gridgraphics=0.5_1=r44hc72bb7e_3
  - r-gtable=0.3.6=r44hc72bb7e_0
  - r-hms=1.1.3=r44hc72bb7e_2
  - r-httr2=1.2.1=r44hc72bb7e_0
  - r-isoband=0.2.7=r44ha18555a_3
  - r-jsonlite=2.0.0=r44h2b5f3a1_0
  - r-labeling=0.4.3=r44hc72bb7e_1
  - r-lattice=0.22_7=r44h2b5f3a1_0
  - r-lazyeval=0.2.2=r44hb1dbf0f_5
  - r-lifecycle=1.0.4=r44hc72bb7e_1
  - r-magrittr=2.0.3=r44hb1dbf0f_3
  - r-mass=7.3_64=r44h2b5f3a1_0
  - r-matrix=1.7_3=r44h2ae2be5_0
  - r-mgcv=1.9_3=r44h2ae2be5_0
  - r-munsell=0.5.1=r44hc72bb7e_1
  - r-nlme=3.1_168=r44hb67ce94_0
  - r-openssl=2.3.3=r44he8289e2_0
  - r-patchwork=1.3.1=r44hc72bb7e_0
  - r-pillar=1.11.0=r44hc72bb7e_0
  - r-pkgconfig=2.0.3=r44hc72bb7e_4
  - r-prettyunits=1.2.0=r44hc72bb7e_1
  - r-progress=1.2.3=r44hc72bb7e_1
  - r-purrr=1.1.0=r44h54b55ab_0
  - r-r6=2.6.1=r44hc72bb7e_0
  - r-rappdirs=0.3.3=r44hb1dbf0f_3
  - r-rcolorbrewer=1.1_3=r44h785f33e_3
  - r-rcpp=1.1.0=r44h93ab643_0
  - r-readr=2.1.5=r44h0d4f4ea_1
  - r-rlang=1.1.6=r44h93ab643_0
  - r-scales=1.4.0=r44hc72bb7e_0
  - r-stringi=1.8.7=r44h3c328a7_0
  - r-stringr=1.5.1=r44h785f33e_1
  - r-sys=3.4.3=r44h2b5f3a1_0
  - r-tibble=3.3.0=r44h2b5f3a1_0
  - r-tidyr=1.3.1=r44h0d4f4ea_1
  - r-tidyselect=1.2.1=r44hc72bb7e_1
  - r-tidytree=0.4.6=r44hc72bb7e_1
  - r-tzdb=0.5.0=r44h93ab643_0
  - r-utf8=1.2.6=r44h2b5f3a1_0
  - r-vctrs=0.6.5=r44h0d4f4ea_1
  - r-viridis=0.6.5=r44hc72bb7e_1
  - r-viridislite=0.4.2=r44hc72bb7e_2
  - r-vroom=1.6.5=r44h0d4f4ea_1
  - r-withr=3.0.2=r44hc72bb7e_0
  - r-yulab.utils=0.2.0=r44hc72bb7e_0
  - ragtag=2.1.0=pyhb7b1952_0
  - raxml=8.2.13=h7b50bb2_3
  - raxml-ng=1.2.2=h6747034_2
  - rich=14.1.0=pyhe01879c_0
  - samtools=1.22=h96c455f_0
  - scipy=1.16.0=py311h2d3ef60_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - sepp=4.5.5=py311haab0aaa_3
  - seqkit=2.10.1=he881be0_0
  - seqtk=1.5=h577a1d6_1
  - setuptools=80.9.0=pyhff2d567_0
  - snakemake=9.6.0=hdfd78af_0
  - snakemake-executor-plugin-cluster-generic=1.0.9=pyhdfd78af_0
  - snakemake-interface-common=1.21.0=pyhdfd78af_0
  - snakemake-interface-executor-plugins=9.3.9=pyhdfd78af_0
  - snakemake-interface-logger-plugins=1.2.4=pyhdfd78af_0
  - snakemake-interface-report-plugins=1.2.0=pyhdfd78af_0
  - snakemake-interface-storage-plugins=4.2.2=pyhdfd78af_0
  - snakemake-minimal=9.6.0=pyhdfd78af_0
  - spades=4.2.0=h8d6e82b_1
  - sqlite=3.50.4=hbc0de68_0
  - sra-tools=3.2.1=h4304569_1
  - statsmodels=0.14.5=py311hb0beb2c_0
  - tk=8.6.13=noxft_hd72426e_102
  - tktable=2.10=h8d826fa_7
  - trimal=1.5.0=h9948957_2
  - ucsc-fatotwobit=482=hdc0a859_0
  - ucsc-twobitinfo=482=hdc0a859_0
  - wget=1.21.4=hda4d442_0
  - yaml=0.2.5=h280c20c_3
